#!/usr/bin/env bash

config_path=~/.config/git-meta-status.sh

set -euo pipefail

print_help() {
    echo "USAGE: meta ACTION"
    echo " "
    echo "ACTIONS: session-exit     Saves local git states to remote repository"
    echo "         status           Shows all git states of all machines"
    echo "         help             Shows this help"
}

uniq_git_repo_path() {
    remote=`git remote -v | grep origin | tr ' ' '\t' | cut -f2 | head -n 1`
    if [[ "$remote" != *"@"* ]]; then
        host=`echo "$remote" | cut -d'/' -f3`
        repo=`echo "$remote" | cut -d'/' -f4-`

        remote="git@$host:$repo"
    fi
    # keep the part between the '@' and '.git' | replace ':' with '/' 
    echo "$remote" | sed 's/^[a-zA-Z \t]*@//;s/\.git$//' | tr -s ':' '/'
}

meta_pull() {
    if [[ ! -d "$git_meta_path" ]]; then
        echo "WARN: No directory <$git_meta_path> - will try to clone meta remote!"
        git_meta_parent_dir=`echo "$git_meta_path" | rev | cut -d'/' -f2- | rev`
        if [[ ! -z "$git_meta_parent_dir" ]] && [[ ! -d "$git_meta_parent_dir" ]]; then
            echo "WARN: No directory <$git_meta_parent_dir> - creating!"
            mkdir -p "$git_meta_parent_dir"
        fi
        git clone "$git_meta_remote" "$git_meta_path"
    fi
    cd "$git_meta_path" 
    if [[ ! -d ".git" ]]; then
        echo "ERR: <$git_meta_path> is not a repository - please remove <$git_meta_path> directory to enable clone."
        print_help
        exit 5
    fi
    git pull 
    cd "$save_dir" 
}

meta_record() {
    if [[ ! -d "$git_dir_path" ]]; then 
        echo "ERR: git_dir_path <$git_dir_path> does not exist"
        print_help
        exit 3
    fi
    if [[ ! -d "$git_meta_path" ]]; then
        echo "ERR: Directory <$git_meta_path> does not exist"
        print_help
        exit 4
    fi
    cd "$git_dir_path" 
    for repo in *; do
        cd "$git_dir_path/$repo"
        echo "REPO:"
        echo "$git_dir_path/$repo"
        if [[ ! -d .git ]]; then
            echo "WARN: <$git_dir_path/$repo> is not a git repository - skipping!"
            continue
        fi
        
        path="$git_meta_path"/`uniq_git_repo_path`/"$device_id"
        [[ ! -d "$path" ]] && mkdir -p "$path"

        git rev-parse HEAD > "$path/HEAD"
        git rev-parse --short HEAD > "$path/HEAD_short"
        git status --short > "$path/status_short"
        git cherry -v > "$path/cherry_v"
    done
    cd "$save_dir"
}

meta_commit() {
    if ! git diff-index --quiet HEAD; then
        echo "WARN: Git states did not change - nothing to commit."
        return
    fi

    cd "$git_meta_path" 
    git add .
    git commit -m "Device: $device_id"
    cd "$save_dir" 
}

meta_push() {
    if [[ ! -d "$git_meta_path" ]]; then 
        echo "ERR: git_meta_path <$git_meta_path> does not exist"
        print_help
        exit 3
    fi
    cd "$git_meta_path" 

    if [[ -z "`git cherry -v`" ]]; then
        echo "WARN: Git states did not change - nothing to push."
    else
        git push 
    fi

    cd "$save_dir" 
}

if [ $# -ne 1 ]; then
    echo "ERR: Wrong number of arguments - required 1, found <$#>"
    print_help
    exit 1
fi

# default config
git_path=~/git
git_meta_path=~/.cache/git-meta-status

# load config if exists
if [ -f "$config_path" ]; then 
    source "$config_path"
else
    echo "WARN: config file <$config_path> does not exist"\
         " - consider creating it."
fi

save_dir=`pwd`

case $1 in
    session-exit)
        meta_pull
        meta_record
        meta_commit
        meta_push
        ;;
    status)
        echo "ERR: Not implemented :("
        print_help
        exit 42
        ;;
    help)
        print_help
        exit 0
        ;;
    *)
        echo "ERR: Invalid action <$1>"
        print_help
        exit 2
        ;;
esac

